language: cpp
env:
  matrix:
    # we only use linux to gen bindings and cocos files
  - GEN_BINDING=YES
  - GEN_COCOS_FILES=YES
os:
  - linux
  - osx
script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

# whitelist
branches:
  only:
    - develop
